- name: Install Apache config file
  template: src=php-project.conf dest=/etc/httpd/conf.d/php-project.conf mode=0644
  notify: restart httpd

- name: Install remount-mnt-project.sh
  template: src=remount-mnt-project.sh dest=/etc/init.d/remount-mnt-project.sh mode=0755

- name: Install remount-mnt-project.service
  template: src=remount-mnt-project.service dest=/etc/systemd/system/remount-mnt-project.service mode=0644

- name: Enable remount-mnt-project.service
  command: systemctl enable remount-mnt-project

- name: Run remount-mnt-project.sh
  command: systemctl start remount-mnt-project

- name: Create symlink to /mnt/project
  file: src=/mnt/project dest=/home/vagrant/project state=link

- name: Create MariaDB databases
  mysql_db: login_user=root login_password={{ mariadb_root_password }} db={{ item.dbname }} state=present encoding=utf8mb4
  with_items:
    - "{{ mariadb_db }}"

- name: Install MariaDB server.cnf
  template: src=mariadb-server.cnf.j2 dest=/etc/my.cnf.d/server.cnf mode=0644

- name: Create MariaDB slow query log file
  shell: "touch {{ mariadb_slow_query_log_file }} creates={{ mariadb_slow_query_log_file }}"

- name: Set ownership on slow query log file
  file:
    path: "{{ mariadb_slow_query_log_file }}"
    state: file
    owner: mysql
    group: mysql
    mode: 0644

- name: Create MariaDB general log file
  shell: "touch {{ mariadb_general_query_log_file }} creates={{ mariadb_general_query_log_file }}"

- name: Set ownership on general query log file
  file:
    path: "{{ mariadb_general_query_log_file }}"
    state: file
    owner: mysql
    group: mysql
    mode: 0644
  notify:
    - restart mariadb-server
