# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  config.ssh.forward_x11 = true
  os=["centos/7","bento/centos-6.9","suse/sles12sp2","bento/ubuntu-16.04"]
  # using the 'os' array above, you can specify one or more boxes to start up
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true, rsync__exclude: ["devops"]
 M=0
  N=0
  (M..N).each do |machine_id|
    config.vm.define "vagrant#{machine_id}" do |machine|
      machine.vm.box = os["#{machine_id}".to_i]
      machine.vm.network "private_network", ip: "10.0.15.10#{machine_id}",
         virtualbox__intnet: true
      machine.vm.provider "virtualbox" do |v|
        v.memory = 4096
      end
      if machine_id == N
        machine.vm.provision :ansible do |ansible|
           ansible.playbook = 'vagrant.yml'
##         ansible.extra_vars = "devops/host_vars/vagrant#{machine_id}"
           ansible.raw_arguments = ['--diff']
        end
      end
    end
  end 
end
