# See http://blog.remirepo.net/pages/Config-en

- name: Install epel repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install remi repo
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present

- name: Check PHP installed
  shell: | 
    test `rpm -qa | grep ^php-[0-9] | sed -e 's/\.//g' | cut -c5-6` = `echo {{ php_remi_repo }} | cut -c9-10`
  register: result
  failed_when: result.rc not in [0, 1, 2]

- name: Remove exsiting PHP
  yum: pkg={{ item }} state=absent
  with_items:
    - "php*"
  when: result.rc != 0

- name: Instal PHP
  yum: pkg={{ item }} enablerepo=remi,{{ php_remi_repo }} state=present
  with_items:
    - php
    - php-mbstring
    - php-gd
    - php-mcrypt
    - php-mysqlnd
    - php-pear
    - php-xml
    - php-pecl-xdebug
    - php-opcache
    - php-pecl-apcu
    - php-intl
  when: result.rc != 0

- name: Update php.ini
  template: src=php.ini-{{ php_remi_repo }}.j2 dest=/etc/php.ini

- name: Update xdebug.ini
  template: src=xdebug.ini dest=/etc/php.d/15-xdebug.ini
  notify: restart httpd
